# Generated by Django 3.0.3 on 2020-02-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='patient',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='reason',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Reason',
        ),
    ]
