# Generated by Django 3.0.3 on 2020-02-24 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_auto_20200224_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='reason',
            field=models.CharField(choices=[('blood_pressure', 'YOu have high blood pressure'), ('general_concern', 'we are just worried about you')], max_length=100),
        ),
    ]
