# Generated by Django 3.0.3 on 2020-02-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_auto_20200224_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='request',
            name='open',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
