# Generated by Django 3.0.3 on 2020-02-25 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0005_auto_20200225_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med.Reason'),
        ),
    ]
