# Generated by Django 3.0.3 on 2020-02-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0006_auto_20200225_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='rasa_conversation_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='patient',
            field=models.CharField(default='+18573028782', max_length=100),
        ),
    ]
